export const CURRENCIES_LIST_REQUEST = 'CURRENCIES_LIST_REQUEST'
export const CURRENCIES_LIST_FAILURE = 'CURRENCIES_LIST_FAILURE'
export const CURRENCIES_LIST_SUCCESS = 'CURRENCIES_LIST_SUCCESS'

export const ADMIN_SETTINGS_REQUEST = 'ADMIN_SETTINGS_REQUEST'
export const ADMIN_SETTINGS_SUCCESS = 'ADMIN_SETTINGS_SUCCESS'
export const ADMIN_SETTINGS_FAILURE = 'ADMIN_SETTINGS_FAILURE'

export const UPDATE_ADMIN_SETTINGS_REQUEST = 'UPDATE_ADMIN_SETTINGS_REQUEST'
export const UPDATE_ADMIN_SETTINGS_SUCCESS = 'UPDATE_ADMIN_SETTINGS_SUCCESS'
export const UPDATE_ADMIN_SETTINGS_FAILURE = 'UPDATE_ADMIN_SETTINGS_FAILURE'
