export const CURRENCIES_LIST_REQUEST = 'CURRENCIES_LIST_REQUEST'
export const CURRENCIES_LIST_FAILURE = 'CURRENCIES_LIST_FAILURE'
export const CURRENCIES_LIST_SUCCESS = 'CURRENCIES_LIST_SUCCESS'

export const ADMIN_SETTINGS_REQUEST = 'ADMIN_SETTINGS_REQUEST'
export const ADMIN_SETTINGS_SUCCESS = 'ADMIN_SETTINGS_SUCCESS'
export const ADMIN_SETTINGS_FAILURE = 'ADMIN_SETTINGS_FAILURE'

export const UPDATE_ADMIN_SETTINGS_REQUEST = 'UPDATE_ADMIN_SETTINGS_REQUEST'
export const UPDATE_ADMIN_SETTINGS_FAILURE = 'UPDATE_ADMIN_SETTINGS_FAILURE'
export const UPDATE_ADMIN_SETTINGS_SUCCESS = 'UPDATE_ADMIN_SETTINGS_SUCCESS'

export const FETCH_NEW_RATES_REQUEST = 'FETCH_NEW_RATES_REQUEST'
export const FETCH_NEW_RATES_SUCCESS = 'FETCH_NEW_RATES_SUCCESS'
export const FETCH_NEW_RATES_FAILURE = 'FETCH_NEW_RATES_FAILURE'

export const RESET_NOTIFICATION = 'RESET_NOTIFICATION'

export const BUY_CURRENCY_REQUEST = 'BUY_CURRENCY_REQUEST'
export const BUY_CURRENCY_SUCCESS = 'BUY_CURRENCY_SUCCESS'
export const BUY_CURRENCY_FAILURE = 'BUY_CURRENCY_FAILURE'

export const SELL_CURRENCY_REQUEST = 'SELL_CURRENCY_REQUEST'
export const SELL_CURRENCY_SUCCESS = 'SELL_CURRENCY_SUCCESS'
export const SELL_CURRENCY_FAILURE = 'SELL_CURRENCY_FAILURE'
